### ISSUE TITLE
Trying to rotate a piece while it is against a wall causes an exception

### ISSUE THREAD

**Issue by AlexPieczynski** [AlexPieczynski/TotallyNotTetris#1]
There is a java.lang.ArrayIndexOutOfBoundsException in canRotate() when trying to rotate while next  to a wall. The program still executes properly, but an exception message is printed in the console. Not a huge deal, but probably worth fixing.

So the piece is blocked from rotating, which is GOOD, we just probably don't want the exception message.

**Comment by bcarve2** [comment]
this probably comes from the program checking a location that is out of bounds. we could use a try-catch for this

**Comment by aherna71** [comment]
Fixed in the latest push using try-catch statements. No longer prints Exception to the console window.
